#!/usr/bin/env python3
"""Generate independent C++ toolchain and API skill routes."""

from __future__ import annotations

import argparse
import json
import re
import tempfile
from pathlib import Path


CPP_PATH = r"(?i:\.(c|cc|cpp|cxx|h|hh|hpp|hxx|ixx))$"
BUILD_PATH = r"(?i:(^|/)(CMakeLists\.txt|CMakePresets\.json|[^/]+\.cmake))$"
TEST_PATH = r"(?i:(^|/)(tests?|test)/.*\.(c|cc|cpp|cxx|h|hh|hpp|hxx)|(_test|_tests)\.(c|cc|cpp|cxx))$"
WINDOWS_RESOURCE_PATH = r"(?i:\.(rc|manifest))$"
MSVC_BUILD_PATH = r"(?i:\.(vcxproj|props|targets|sln|slnx))$"
TOOLCHAINS = ("gpp", "msvc")
APIS = ("win32",)
LEGACY_KINDS = ("generic", "portable", "gcc", "gpp", "windows")
LEGACY_LAYERS = ("gcc", "windows")


def normalize(toolchain: str | None = None, apis: list[str] | tuple[str, ...] = ()) -> tuple[str | None, tuple[str, ...]]:
    if toolchain not in (None, *TOOLCHAINS):
        raise ValueError(f"unknown toolchain: {toolchain}")
    unknown = set(apis) - set(APIS)
    if unknown:
        raise ValueError(f"unknown API selection(s): {', '.join(sorted(unknown))}")
    return toolchain, tuple(api for api in APIS if api in apis)


def legacy_selection(kind: str | None = None, layers: list[str] | tuple[str, ...] = ()) -> tuple[str | None, tuple[str, ...]]:
    if kind:
        if kind not in LEGACY_KINDS:
            raise ValueError(f"unknown legacy kind: {kind}")
        if kind in ("generic", "portable"):
            return normalize()
        if kind in ("gcc", "gpp"):
            return normalize("gpp")
        return normalize("msvc", ["win32"])
    unknown = set(layers) - set(LEGACY_LAYERS)
    if unknown:
        raise ValueError(f"unknown legacy layer(s): {', '.join(sorted(unknown))}")
    toolchain = "gpp" if "gcc" in layers else ("msvc" if "windows" in layers else None)
    apis = ["win32"] if "windows" in layers else []
    return normalize(toolchain, apis)


def compatibility_kind(toolchain: str | None, apis: tuple[str, ...]) -> str:
    if toolchain is None and not apis:
        return "generic"
    if toolchain == "gpp" and not apis:
        return "gpp"
    if toolchain == "msvc" and apis == ("win32",):
        return "windows"
    return "composed"


def routes(toolchain: str | None = None, apis: list[str] | tuple[str, ...] = ()) -> dict:
    toolchain, apis = normalize(toolchain, apis)
    result = [
        {"path": CPP_PATH, "skills": ["cpp:cpp-style"], "note": "C++ source floor."},
        {"path": BUILD_PATH, "skills": ["cpp:cpp-build", "cpp:cpp-libraries"]},
        {"path": TEST_PATH, "skills": ["cpp:cpp-testing"]},
    ]
    if toolchain == "gpp":
        result.append({"path": rf"{CPP_PATH}|{BUILD_PATH}", "skills": ["gpp:gpp-toolchain"], "note": "Explicit G++ toolchain selection."})
    if toolchain == "msvc":
        result.append({"path": rf"{CPP_PATH}|{BUILD_PATH}|{MSVC_BUILD_PATH}", "skills": ["msvc:msvc-toolchain"], "note": "Explicit MSVC/clang-cl toolchain selection."})
    if "win32" in apis:
        result.append({"path": rf"{CPP_PATH}|{WINDOWS_RESOURCE_PATH}", "skills": ["win32:windows-overview", "win32:win32-style"], "note": "Explicit user-mode Win32 API selection; compiler remains independent."})
    layers = ["cpp", *([toolchain] if toolchain else []), *apis]
    return {
        "_comment": [
            "Generated by tomjseery/cpp-agents .agents/gen_skill_routes.py; do not edit by hand.",
            "Toolchain and API selections are independent. Host OS never chooses a compiler.",
            "Every matching technical route fires; no process plugin is required.",
        ],
        "kind": compatibility_kind(toolchain, apis),
        "profile": {"toolchain": toolchain, "apis": list(apis)},
        "layers": layers,
        "routes": result,
    }


def routes_from_legacy(kind: str | None = None, layers: list[str] | tuple[str, ...] = ()) -> dict:
    toolchain, apis = legacy_selection(kind, layers)
    return routes(toolchain, apis)


def rendered(toolchain: str | None = None, apis: list[str] | tuple[str, ...] = ()) -> str:
    return json.dumps(routes(toolchain, apis), indent=2, ensure_ascii=False) + "\n"


def target_for(root: Path) -> Path:
    return root / ".agents" / "skill-routes.json"


def skills_for(toolchain: str | None, apis: list[str] | tuple[str, ...], path: str) -> set[str]:
    matched: set[str] = set()
    for route in routes(toolchain, apis)["routes"]:
        if re.search(route["path"], path):
            matched.update(route.get("skills") or [])
    return matched


def write_or_check(toolchain: str | None, apis: list[str], root: Path, check: bool) -> int:
    target = target_for(root)
    expected = rendered(toolchain, apis)
    if check:
        actual = target.read_text(encoding="utf-8") if target.is_file() else None
        if actual != expected:
            print(f"STALE: {target}")
            return 1
        print(f"current: {target}")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated: {target} ({'+'.join(routes(toolchain, apis)['layers'])})")
    return 0


def self_test() -> int:
    profiles = [(None, []), ("gpp", []), ("msvc", []), (None, ["win32"]), ("gpp", ["win32"]), ("msvc", ["win32"])]
    with tempfile.TemporaryDirectory() as temporary:
        for index, (toolchain, apis) in enumerate(profiles):
            root = Path(temporary) / str(index)
            if write_or_check(toolchain, apis, root, False) or write_or_check(toolchain, apis, root, True):
                return 1
    if legacy_selection("windows") != ("msvc", ("win32",)) or legacy_selection("gcc") != ("gpp", ()):
        print("legacy profile normalization failed")
        return 1
    cases = {
        ((None, ()), "src/main.cpp"): {"cpp:cpp-style"},
        (("msvc", ()), "src/main.cpp"): {"cpp:cpp-style", "msvc:msvc-toolchain"},
        (("msvc", ()), "app/app.rc"): set(),
        ((None, ("win32",)), "src/main.cpp"): {"cpp:cpp-style", "win32:windows-overview", "win32:win32-style"},
        ((None, ("win32",)), "app/app.vcxproj"): set(),
        (("gpp", ("win32",)), "src/main.cpp"): {"cpp:cpp-style", "gpp:gpp-toolchain", "win32:windows-overview", "win32:win32-style"},
        ((None, ()), "tests/core_test.cpp"): {"cpp:cpp-style", "cpp:cpp-testing"},
        ((None, ()), "CMakeLists.txt"): {"cpp:cpp-build", "cpp:cpp-libraries"},
        (("msvc", ()), "lib/lib.vcxproj"): {"msvc:msvc-toolchain"},
    }
    for ((toolchain, apis), path), expected in cases.items():
        actual = skills_for(toolchain, apis, path)
        if actual != expected:
            print(f"unexpected skills for {toolchain}/{apis}:{path}: {sorted(actual)}")
            return 1
    print("skill-route generator self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--toolchain", choices=TOOLCHAINS)
    parser.add_argument("--api", action="append", choices=APIS, default=[])
    parser.add_argument("--kind", choices=LEGACY_KINDS)
    parser.add_argument("--layer", action="append", choices=LEGACY_LAYERS, default=[])
    parser.add_argument("--into", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        if any((args.toolchain, args.api, args.kind, args.layer, args.into, args.check)):
            parser.error("--self-test cannot be combined with generation arguments")
        return self_test()
    if (args.kind or args.layer) and (args.toolchain or args.api):
        parser.error("legacy --kind/--layer cannot be combined with --toolchain/--api")
    if not args.into:
        parser.error("--into is required")
    toolchain, apis = legacy_selection(args.kind, args.layer) if (args.kind or args.layer) else normalize(args.toolchain, args.api)
    return write_or_check(toolchain, list(apis), args.into.resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
