#!/usr/bin/env python3
"""Generate layered C++ skill routes consumed by concertable's write hook."""

import argparse
import json
import re
import tempfile
from pathlib import Path


CPP_PATH = r"\.(c|cc|cpp|cxx|h|hh|hpp|hxx|ixx)$"
BUILD_PATH = r"(^|/)(CMakeLists\.txt|CMakePresets\.json|[^/]+\.cmake)$"
TEST_PATH = r"(^|/)(tests?|test)/.*\.(c|cc|cpp|cxx|h|hh|hpp|hxx)$|(_test|_tests)\.(c|cc|cpp|cxx)$"
KIND_ALIASES = {"portable": "generic", "gpp": "gcc"}
CANONICAL_KINDS = ("generic", "gcc", "windows")


def canonical_kind(kind: str) -> str:
    return KIND_ALIASES.get(kind, kind)


def routes(kind: str) -> dict:
    kind = canonical_kind(kind)
    result = [
        {
            "path": CPP_PATH,
            "skills": ["base:cpp-style"],
            "note": "C++ source floor. More specific routes add to this skill; they do not replace it.",
        },
        {
            "path": BUILD_PATH,
            "skills": ["base:cpp-build", "base:cpp-libraries"],
        },
        {
            "path": TEST_PATH,
            "skills": ["base:cpp-testing"],
        },
        {
            "path": r"(^|/)(AGENTS|CLAUDE)\.md$",
            "skills": ["concertable:docs-and-debt"],
        },
        {
            "path": r"^\.agents/skill-routes\.json$",
            "skills": ["concertable:skill-routes"],
        },
    ]

    if kind == "gcc":
        result.append(
            {
                "path": rf"{CPP_PATH}|{BUILD_PATH}",
                "skills": ["gcc:gcc-toolchain"],
                "note": "GCC/Linux toolchain layer generated for a gcc project.",
            }
        )
    elif kind == "windows":
        result.extend(
            [
                {
                    "path": rf"{CPP_PATH}|\.(rc|manifest)$",
                    "skills": [
                        "windows:windows-overview",
                        "windows:win32-style",
                    ],
                    "note": "Native Windows layer generated for an MSVC/clang-cl/Win32 project.",
                },
                {
                    "path": BUILD_PATH,
                    "skills": ["windows:windows-overview"],
                },
            ]
        )

    return {
        "_comment": [
            "Generated by tomjseery/cpp-agents .agents/gen_skill_routes.py; do not edit by hand.",
            "The concertable plugin reads this table before writes and reviews.",
            "Every matching route fires, so platform and test/build routes layer on the C++ base.",
        ],
        "kind": kind,
        "routes": result,
    }


def rendered(kind: str) -> str:
    return json.dumps(routes(kind), indent=2, ensure_ascii=False) + "\n"


def target_for(root: Path) -> Path:
    return root / ".agents" / "skill-routes.json"


def skills_for(kind: str, path: str) -> set[str]:
    matched = set()
    for route in routes(kind)["routes"]:
        if re.search(route["path"], path):
            matched.update(route.get("skills") or [])
    return matched


def write_or_check(kind: str, root: Path, check: bool) -> int:
    canonical = canonical_kind(kind)
    target = target_for(root)
    expected = rendered(canonical)
    if check:
        try:
            actual = target.read_text(encoding="utf-8")
        except OSError:
            actual = None
        if actual != expected:
            print(f"STALE: {target}; regenerate with --kind {canonical} --into {root}")
            return 1
        print(f"current: {target} ({canonical})")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated: {target} ({canonical})")
    return 0


def self_test() -> int:
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        for kind in CANONICAL_KINDS:
            destination = root / kind
            if write_or_check(kind, destination, False) != 0:
                return 1
            if write_or_check(kind, destination, True) != 0:
                return 1
            parsed = json.loads(target_for(destination).read_text(encoding="utf-8"))
            if parsed["kind"] != kind or not parsed["routes"]:
                return 1

        if routes("portable")["kind"] != "generic" or routes("gpp")["kind"] != "gcc":
            print("legacy kind aliases do not normalize to canonical kinds")
            return 1

        cases = {
            ("generic", "app/src/main.cpp"): {"base:cpp-style"},
            ("generic", "tests/core/core_test.cpp"): {
                "base:cpp-style",
                "base:cpp-testing",
            },
            ("generic", "CMakeLists.txt"): {
                "base:cpp-build",
                "base:cpp-libraries",
            },
            ("gcc", "libs/core/src/core.cpp"): {
                "base:cpp-style",
                "gcc:gcc-toolchain",
            },
            ("windows", "app/src/main.cpp"): {
                "base:cpp-style",
                "windows:windows-overview",
                "windows:win32-style",
            },
            ("windows", "app/app.manifest"): {
                "windows:windows-overview",
                "windows:win32-style",
            },
            ("generic", "AGENTS.md"): {"concertable:docs-and-debt"},
            ("generic", ".agents/skill-routes.json"): {"concertable:skill-routes"},
        }
        for (kind, path), expected in cases.items():
            actual = skills_for(kind, path)
            if actual != expected:
                print(f"unexpected skills for {kind}:{path}: {sorted(actual)}")
                return 1
    print("skill-route generator self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kind", choices=(*CANONICAL_KINDS, *KIND_ALIASES))
    parser.add_argument("--into", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        if args.kind or args.into or args.check:
            parser.error("--self-test cannot be combined with generation arguments")
        return self_test()
    if not args.kind or not args.into:
        parser.error("--kind and --into are required unless --self-test is used")
    return write_or_check(args.kind, args.into.resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
