#!/usr/bin/env python3
"""Generate layered C++ skill routes consumed by concertable's write hook."""

import argparse
import json
import re
import tempfile
from pathlib import Path


CPP_PATH = r"(?i:\.(c|cc|cpp|cxx|h|hh|hpp|hxx|ixx))$"
BUILD_PATH = r"(?i:(^|/)(CMakeLists\.txt|CMakePresets\.json|[^/]+\.cmake))$"
TEST_PATH = r"(?i:(^|/)(tests?|test)/.*\.(c|cc|cpp|cxx|h|hh|hpp|hxx)|(_test|_tests)\.(c|cc|cpp|cxx))$"
WINDOWS_RESOURCE_PATH = r"(?i:\.(rc|manifest))$"
KIND_ALIASES = {"portable": "generic", "gpp": "gcc"}
CANONICAL_KINDS = ("generic", "gcc", "windows")
PLATFORM_LAYERS = ("windows", "gcc")


def canonical_kind(kind: str) -> str:
    return KIND_ALIASES.get(kind, kind)


def canonical_layers(value: str | list[str] | tuple[str, ...]) -> tuple[str, ...]:
    if isinstance(value, str):
        kind = canonical_kind(value)
        if kind not in CANONICAL_KINDS:
            raise ValueError(f"unknown project kind: {value}")
        requested = () if kind == "generic" else (kind,)
    else:
        requested = tuple(value)
        unknown = set(requested) - set(PLATFORM_LAYERS)
        if unknown:
            raise ValueError(f"unknown platform layer(s): {', '.join(sorted(unknown))}")
    return ("base", *(layer for layer in PLATFORM_LAYERS if layer in requested))


def compatibility_kind(layers: tuple[str, ...]) -> str:
    platforms = layers[1:]
    if not platforms:
        return "generic"
    if len(platforms) == 1:
        return platforms[0]
    return "composed"


def routes(kind_or_layers: str | list[str] | tuple[str, ...]) -> dict:
    layers = canonical_layers(kind_or_layers)
    result = [
        {
            "path": CPP_PATH,
            "skills": ["base:cpp-style"],
            "note": "C++ source floor. More specific routes add to this skill; they do not replace it.",
        },
        {
            "path": BUILD_PATH,
            "skills": ["base:cpp-build", "base:cpp-libraries"],
        },
        {
            "path": TEST_PATH,
            "skills": ["base:cpp-testing"],
        },
        {
            "path": r"(^|/)(AGENTS|CLAUDE)\.md$",
            "skills": ["concertable:docs-and-debt"],
        },
        {
            "path": r"^\.agents/skill-routes\.json$",
            "skills": ["concertable:skill-routes"],
        },
    ]

    if "gcc" in layers:
        result.append(
            {
                "path": rf"{CPP_PATH}|{BUILD_PATH}",
                "skills": ["gcc:gcc-toolchain"],
                "note": "GCC/Linux toolchain layer generated for a gcc project.",
            }
        )
    if "windows" in layers:
        result.extend(
            [
                {
                    "path": rf"{CPP_PATH}|{WINDOWS_RESOURCE_PATH}",
                    "skills": [
                        "windows:windows-overview",
                        "windows:win32-style",
                    ],
                    "note": "Native Windows layer generated for an MSVC/clang-cl/Win32 project.",
                },
                {
                    "path": BUILD_PATH,
                    "skills": ["windows:windows-overview", "windows:win32-style"],
                },
            ]
        )

    return {
        "_comment": [
            "Generated by tomjseery/cpp-agents .agents/gen_skill_routes.py; do not edit by hand.",
            "The concertable plugin reads this table before writes and reviews.",
            "Every matching route fires, so platform and test/build routes layer on the C++ base.",
        ],
        "kind": compatibility_kind(layers),
        "layers": list(layers),
        "routes": result,
    }


def rendered(kind_or_layers: str | list[str] | tuple[str, ...]) -> str:
    return json.dumps(routes(kind_or_layers), indent=2, ensure_ascii=False) + "\n"


def target_for(root: Path) -> Path:
    return root / ".agents" / "skill-routes.json"


def skills_for(kind_or_layers: str | list[str] | tuple[str, ...], path: str) -> set[str]:
    matched = set()
    for route in routes(kind_or_layers)["routes"]:
        if re.search(route["path"], path):
            matched.update(route.get("skills") or [])
    return matched


def write_or_check(kind_or_layers: str | list[str] | tuple[str, ...], root: Path, check: bool) -> int:
    layers = canonical_layers(kind_or_layers)
    target = target_for(root)
    expected = rendered(layers[1:])
    label = "+".join(layers)
    if check:
        try:
            actual = target.read_text(encoding="utf-8")
        except OSError:
            actual = None
        if actual != expected:
            arguments = " ".join(f"--layer {layer}" for layer in layers[1:]) or "--kind generic"
            print(f"STALE: {target}; regenerate with {arguments} --into {root}")
            return 1
        print(f"current: {target} ({label})")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated: {target} ({label})")
    return 0


def self_test() -> int:
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        for kind in CANONICAL_KINDS:
            destination = root / kind
            if write_or_check(kind, destination, False) != 0:
                return 1
            if write_or_check(kind, destination, True) != 0:
                return 1
            parsed = json.loads(target_for(destination).read_text(encoding="utf-8"))
            if parsed["kind"] != kind or parsed["layers"][0] != "base" or not parsed["routes"]:
                return 1

        if routes("portable")["kind"] != "generic" or routes("gpp")["kind"] != "gcc":
            print("legacy kind aliases do not normalize to canonical kinds")
            return 1

        composed = routes(["windows", "gcc"])
        if composed["kind"] != "composed" or composed["layers"] != ["base", "windows", "gcc"]:
            print("platform layers do not compose in canonical order")
            return 1

        cases = {
            ("generic", "app/src/main.cpp"): {"base:cpp-style"},
            ("generic", "tests/core/core_test.cpp"): {
                "base:cpp-style",
                "base:cpp-testing",
            },
            ("generic", "CMakeLists.txt"): {
                "base:cpp-build",
                "base:cpp-libraries",
            },
            ("gcc", "libs/core/src/core.cpp"): {
                "base:cpp-style",
                "gcc:gcc-toolchain",
            },
            ("windows", "app/src/main.cpp"): {
                "base:cpp-style",
                "windows:windows-overview",
                "windows:win32-style",
            },
            ("windows", "app/app.manifest"): {
                "windows:windows-overview",
                "windows:win32-style",
            },
            ("windows", "app/src/MAIN.CPP"): {
                "base:cpp-style",
                "windows:windows-overview",
                "windows:win32-style",
            },
            ("windows", "app/APP.RC"): {
                "windows:windows-overview",
                "windows:win32-style",
            },
            ("windows", "CMakeLists.txt"): {
                "base:cpp-build",
                "base:cpp-libraries",
                "windows:windows-overview",
                "windows:win32-style",
            },
            (("windows", "gcc"), "app/src/main.cpp"): {
                "base:cpp-style",
                "windows:windows-overview",
                "windows:win32-style",
                "gcc:gcc-toolchain",
            },
            ("generic", "AGENTS.md"): {"concertable:docs-and-debt"},
            ("generic", ".agents/skill-routes.json"): {"concertable:skill-routes"},
        }
        for (kind_or_layers, path), expected in cases.items():
            actual = skills_for(kind_or_layers, path)
            if actual != expected:
                print(f"unexpected skills for {kind_or_layers}:{path}: {sorted(actual)}")
                return 1
    print("skill-route generator self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kind", choices=(*CANONICAL_KINDS, *KIND_ALIASES))
    parser.add_argument("--layer", action="append", choices=PLATFORM_LAYERS, default=[])
    parser.add_argument("--into", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        if args.kind or args.layer or args.into or args.check:
            parser.error("--self-test cannot be combined with generation arguments")
        return self_test()
    if args.kind and args.layer:
        parser.error("--kind is the legacy single-classification input; use repeated --layer for composition")
    if not (args.kind or args.layer) or not args.into:
        parser.error("--kind or at least one --layer, plus --into, are required unless --self-test is used")
    selection = args.kind if args.kind else args.layer
    return write_or_check(selection, args.into.resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
